### ISSUE TITLE
Параметр renderBigPicture

### ISSUE THREAD

**Issue by kirillgenets** [viktorevstigneev/kekstagramm#64]
https://github.com/viktorevstigneev/kekstagramm/blob/474f1d7be8a3e0ccd0e5574f20ea51c6296c1b72/js/main.js#L174
Почему ты передаешь в функцию номер картинки, а не данные о самой картинке? Функция renderBigPicture не должна знать НИЧЕГО о том, что есть какой-то список картинок и т.п., к ней в параметры должны приходить готовые данные.

**Comment by viktorevstigneev** [comment]
ну это пиздец, если я буду передавать данные о самой картинке , придется весь код переделать , раньше бы ты это сказал,я и в душе понятия не имел, что нельзя так делать
