### ISSUE TITLE
Навешивание обработчиков

### ISSUE THREAD

**Issue by kirillgenets** [viktorevstigneev/kekstagramm#85]
https://github.com/viktorevstigneev/kekstagramm/blob/b55a426a572b707748dc051b6dbb55281c15ff84/js/main.js#L145-L148
Если я не ошибаюсь, обработчики можно навесить прямо тут:
https://github.com/viktorevstigneev/kekstagramm/blob/b55a426a572b707748dc051b6dbb55281c15ff84/js/main.js#L114-L126

**Comment by viktorevstigneev** [comment]
не совсем понял где именно,внутри createPhoto?
